-- Drop old procedures with multiple parameters
-- @statement
USE DATABASE CLAUDE_BI;

-- @statement
USE SCHEMA MCP;

-- @statement
DROP PROCEDURE IF EXISTS MCP.DASH_GET_SERIES(TIMESTAMP_TZ, TIMESTAMP_TZ, VARCHAR, VARIANT, VARCHAR);

-- @statement
DROP PROCEDURE IF EXISTS MCP.DASH_GET_TOPN(TIMESTAMP_TZ, TIMESTAMP_TZ, VARCHAR, VARIANT, NUMBER);

-- @statement
DROP PROCEDURE IF EXISTS MCP.DASH_GET_EVENTS(TIMESTAMP_TZ, NUMBER);

-- @statement
DROP PROCEDURE IF EXISTS MCP.DASH_GET_METRICS(TIMESTAMP_TZ, TIMESTAMP_TZ, VARIANT);

-- @statement
DROP PROCEDURE IF EXISTS MCP.LOG_CLAUDE_EVENT(VARIANT, VARCHAR);